# Generated by SmolLM3-3B on 2025-01-01
"""
GGUF LLM Backend for MemOS

This module provides a GGUF LLM backend that integrates with the existing
MemOS LLM factory pattern using ctransformers.
"""

from typing import Any

from string_ai_coding_assistant.memos.configs.llm import BaseLLMConfig
from string_ai_coding_assistant.memos.llms.base import BaseLLM
from string_ai_coding_assistant.memos.llms.model_loader import GGUFModelManager, CTRANSFORMERS_AVAILABLE
from string_ai_coding_assistant.memos.log import get_logger
from string_ai_coding_assistant.memos.types import MessageList

logger = get_logger(__name__)


class GGUFLLLM(BaseLLM):
    """
    GGUF LLM backend class that integrates with MemOS LLM factory.
    
    This class provides a standardized interface for GGUF models using
    ctransformers, following the MemOS LLM pattern.
    """
    
    def __init__(self, config: BaseLLMConfig):
        """
        Initialize the GGUF LLM backend.
        
        Args:
            config (BaseLLMConfig): LLM configuration containing model path and parameters
        """
        self.config = config
        
        # Extract model path from config
        model_path = getattr(config, 'model_name_or_path', None)
        if not model_path:
            raise ValueError("model_name_or_path must be specified in config")
        
        # Extract GGUF-specific configuration
        gguf_config = {
            'max_new_tokens': getattr(config, 'max_tokens', 512),
            'temperature': getattr(config, 'temperature', 0.7),
            'top_p': getattr(config, 'top_p', 0.9),
            'top_k': getattr(config, 'top_k', 50),
            'repetition_penalty': getattr(config, 'repetition_penalty', 1.1),
            'gpu_layers': getattr(config, 'gpu_layers', 0),
            'threads': getattr(config, 'threads', None),
            'context_length': getattr(config, 'context_length', 2048),
        }
        
        # Remove None values
        gguf_config = {k: v for k, v in gguf_config.items() if v is not None}
        
        # Initialize model manager
        self.model_manager = GGUFModelManager(model_path, gguf_config)
        
        # Auto-load model during initialization
        if not self.model_manager.load_model():
            raise RuntimeError(f"Failed to load GGUF model from: {model_path}")
        
        logger.info(f"GGUF LLM backend initialized with model: {model_path}")
    
    def generate(self, messages: MessageList, **kwargs) -> str:
        """
        Generate a response from the GGUF model.
        
        Args:
            messages (MessageList): List of message dicts containing 'role' and 'content'
            **kwargs: Additional generation parameters
            
        Returns:
            str: Generated response
        """
        if not CTRANSFORMERS_AVAILABLE:
            raise RuntimeError("ctransformers library is not available")
        
        if not self.model_manager.is_loaded():
            raise RuntimeError("GGUF model is not loaded")
        
        # Convert messages to a single prompt string
        prompt = self._messages_to_prompt(messages)
        
        try:
            # Generate response using the model manager
            response = self.model_manager.generate(prompt, **kwargs)
            
            # Remove any thinking tags if configured
            if getattr(self.config, 'remove_think_prefix', False):
                response = self._remove_thinking_tags(response)
            
            logger.debug(f"Generated response from GGUF model: {response[:100]}...")
            return response
            
        except Exception as e:
            logger.error(f"Error generating response from GGUF model: {e}")
            raise
    
    def _messages_to_prompt(self, messages: MessageList) -> str:
        """
        Convert message list to a single prompt string.
        
        Args:
            messages (MessageList): List of message dicts
            
        Returns:
            str: Formatted prompt string
        """
        prompt_parts = []
        
        for message in messages:
            role = message.get('role', 'user')
            content = message.get('content', '')
            
            if role == 'system':
                prompt_parts.append(f"System: {content}")
            elif role == 'user':
                prompt_parts.append(f"User: {content}")
            elif role == 'assistant':
                prompt_parts.append(f"Assistant: {content}")
            else:
                prompt_parts.append(f"{role.title()}: {content}")
        
        # Add assistant prompt at the end
        prompt_parts.append("Assistant:")
        
        return "\n".join(prompt_parts)
    
    def _remove_thinking_tags(self, text: str) -> str:
        """
        Remove thinking tags from generated text.
        
        Args:
            text (str): Text potentially containing thinking tags
            
        Returns:
            str: Text with thinking tags removed
        """
        import re
        return re.sub(r"^<think>.*?</think>\s*", "", text, flags=re.DOTALL).strip()
    
    def get_model_info(self) -> dict[str, Any]:
        """
        Get information about the GGUF model.
        
        Returns:
            dict[str, Any]: Model information
        """
        return self.model_manager.get_model_info()
    
    def is_healthy(self) -> bool:
        """
        Check if the GGUF model is loaded and healthy.
        
        Returns:
            bool: True if model is loaded and responsive
        """
        try:
            return self.model_manager.is_loaded()
        except Exception as e:
            logger.error(f"Health check failed for GGUF model: {e}")
            return False
    
    def __del__(self):
        """
        Cleanup model resources when the object is destroyed.
        """
        if hasattr(self, 'model_manager') and self.model_manager:
            self.model_manager.unload_model() 